name: C/C++ CI

on: [push]

matrix:
  os: [windows-latest, ubuntu-latest, macos-latest]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: configure
        run: echo ${{ matrix.os }}
