name: C/C++ CI

on: [push]

jobs:
  build:
    strategy:
      matrix:
        # os: [windows-latest, ubuntu-latest, macos-latest]
        os:
          - name: windows-latest
            vcpkg-bootstrap: .\vcpkg\bootstrap-vcpkg.bat
            vcpkg: .\vcpkg\vcpkg.exe
            env:
              VCPKG_DEFAULT_TRIPLET: x64-windows-static
          - name: ubuntu-latest
            vcpkg-bootstrap: ./vcpkg/bootstrap-vcpkg.sh
            vcpkg: ./vcpkg/vcpkg
            env: {}
          - name: macos-latest
            vcpkg-bootstrap: ./vcpkg/bootstrap-vcpkg.sh
            vcpkg: ./vcpkg/vcpkg
            env: {}

    runs-on: ${{ matrix.os.name }}

    steps:
      - uses: actions/checkout@v2
      - name: Install Ubuntu packages
        run: sudo apt update && sudo apt install libgl1-mesa-dev libasound2-dev
        if: matrix.os.name == 'ubuntu-latest'
      - name: Clone vcpkg
        run: git clone https://github.com/microsoft/vcpkg.git
      - name: Bootstrap vcpkg
        run: ${{ matrix.os.vcpkg-bootstrap }}
      - name: Install dependencies
        run: ${{ matrix.os.vcpkg }} install SDL2 doctest benchmark span-lite glew fmt range-v3
        env: ${{ matrix.os.env }}
      - name: Export vcpkg
        run: ${{ matrix.os.vcpkg }} export --output=gbemu-build-${{ runner.os }} --zip SDL2 doctest benchmark span-lite glew fmt range-v3
        env: ${{ matrix.os.env }}
  release:
    needs: build
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Test
        run: ls
        shell: bash
